remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: KernixOS
description: Micro Kernel
show_downloads: true

